import assert from 'assert'
import svg5 from '../dist/svg5.cjs.js'

const tests = {}
tests.CLOSE = () => {}
tests.CORNER = () => {}
tests.CENTER = () => {}
tests._attrRegex = () => {}
tests._initAlea = () => {}
tests._initSimplexNoise = () => {}
tests._addElement = () => {}
tests._addTransform = () => {}
tests._getTransform = () => {}
tests._round = () => {}
tests._parseColor = () => {}
tests._prng = () => {}
tests._simplex = () => {}
tests.createSVG = () => {}
tests.getHTML = () => {}
tests.render = () => {}
tests.precision = () => {}
tests.addStyle = () => {}
tests.addDef = () => {}
tests.clear = () => {}
tests.background = () => {}
tests.opacity = () => {}
tests.fill = () => {}
tests.noFill = () => {}
tests.stroke = () => {}
tests.strokeWidth = () => {}
tests.strokeWeight = () => {}
tests.strokeCap = () => {}
tests.strokeJoin = () => {}
tests.strokeDashArray = () => {}
tests.noStroke = () => {}
tests.setAttribute = () => {}
tests.removeAttribute = () => {}
tests.clearAttributes = () => {}
tests.ellipseMode = () => {}
tests.circle = () => {}
tests.ellipse = () => {}
tests.rectMode = () => {}
tests.rect = () => {}
tests.square = () => {}
tests.point = () => {}
tests.polyline = () => {}
tests.line = () => {}
tests.polygon = () => {}
tests.triangle = () => {}
tests.quad = () => {}
tests.regularPolygon = () => {}
tests.arc = () => {}
tests.spline = () => {}
tests.beginShape = () => {}
tests.lineTo = () => {}
tests.moveTo = () => {}
tests.vertex = () => {}
tests.bezierVertex = () => {}
tests.cubicVertex = () => {}
tests.quadraticVertex = () => {}
tests.endShape = () => {}
tests.PI = () => {}
tests.TAU = () => {}
tests.lerp = () => {}
tests.norm = () => {}
tests.map = () => {}
tests.constrain = () => {}
tests.radians = () => {}
tests.degrees = () => {}
tests.randomSeed = () => {}
tests.random = () => {}
tests.randInt = () => {}
tests.randBool = () => {}
tests.expRand = () => {}
tests.noiseSeed = () => {}
tests.noise1D = () => {}
tests.noise2D = () => {}
tests.noise3D = () => {}
tests.noise4D = () => {}
tests.noise = () => {}
tests.beginGroup = () => {}
tests.endGroup = () => {}
tests.translate = () => {}
tests.rotate = () => {}
tests.scale = () => {}
tests.push = () => {}
tests.pop = () => {}
tests.save = () => {}
tests.exportPNG = () => {}
tests._name = () => {}
tests._id = () => {}
tests.width = () => {}
tests.height = () => {}
tests.html = () => {}
tests._defs = () => {}
tests._attributes = () => {}
tests._styles = () => {}
tests._fillColor = () => {}
tests._strokeColor = () => {}
tests._strokeWidth = () => {}
tests._strokeCap = () => {}
tests._strokeJoin = () => {}
tests._strokeDashArray = () => {}
tests._opacity = () => {}
tests._transform = () => {}
tests._path = () => {}
tests._rectMode = () => {}
tests._ellipseMode = () => {}
tests._precision = () => {}
tests._svg = () => {}



Object.keys(svg5).filter(key => !tests[key])
    .forEach(key => console.log(`⚠️ Test missing for ${key}`))